services:
  pt-db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: Secret321
      POSTGRES_USER: postgres
      POSTGRES_DB: project_tracker
    command: ["postgres", "-c", "log_statement=all", "-c", "max_connections=400"]
