services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: seCret321
      POSTGRES_USER: pgUser
      POSTGRES_DB: projecttracker
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:5432

volumes:
  pgdata: